nhost/cli

- README.md
- package-lock.json
- package.json
- src/commands/dev.js
- src/commands/init.js
- adds support for custom env vars to be used with Hasura GraphQL engine
> Add support for custom ENV vars on GraphQL engine

- src/commands/init.js
- src/util/projects.js
> Fetch team projects and show them on init

- package-lock.json
- package.json
- src/commands/dev.js
- src/util/compose.js
- src/util/docker-api.js
Manually kills hasura console
Uses new nodeapi with typescript support.
> Terminal halt and TS support

- README.md
- src/commands/init.js
> Get remote extensions dynamically and insert to first up.sql migration

- src/commands/dev.js
> Create .nhost/ folder if not exist on `nhost dev`

- src/commands/dev.js
- src/commands/init.js
- src/util/compose.js
> Add roles, providers and enum data on init

- package.json
- src/commands/dev.js
- src/commands/init.js
- src/util/compose.js
- src/util/config.js
- yarn.lock
Fixes https://github.com/nhost/cli/issues/76, https://github.com/nhost/cli/issues/59
> don't use nunjack for dev/compose

- get.sh
- Streamlined the whole install process (die as early as possible)
- Fixed fringe cases where power is pulled in the middle of install
- Fixed passing release numbers to properly install old releases
- Added comments so that non-bash aficionados can follow along
> Reworked get.sh

- nhost/nhost.go
> update hasura-storage and remove change in path

- .goreleaser.yml
> fix: add a missing `v`

- nhost/nhost.go
> bump hasura version to v2.10.0

- hasura/hasura.go
- nhost/nhost.go
- bump hasura version to v2.10.1
> bump hasura version to v2.10.1

- cmd/compose.go
- cmd/dev.go
- cmd/logs.go
- cmd/root.go
- nhost/utils.go
Fixes permission error which may happen after upgrade on new CLI version
```
Error: open /Users/foobar/my/awesome/project/.nhost/project_name: permission denied
```
> Fix permission issue that may occur for .nhost/project_name file

- nhost/compose/config.go
> Bump nhost/functions to 0.0.4

- nhost/utils.go
Lowercase the name for project
docker compose accepts only lowercase project name
> Lowercase the project name

- cmd/dev.go
- nhost/compose/config.go
- nhost/compose/wrapper.go
- nhost/service/manager.go
- Use nhost/functions:0.1.1
- Change the start order of containers
- Provide a message if it takes too long
> Bump functions docker image to 0.1.1

- nhost/compose/config.go
> Bump nhost/functions to 0.1.2

- cmd/link.go
> fix: prevent changing name to lowercase

- nhost/compose/config.go
> bump hasura auth version

- nhost/compose/config.go
Closes https://github.com/nhost/cli/issues/337
> Bump nhost/functions to 0.1.5

- nhost/compose/config.go
> Bump hasura auth to v0.13.1

- nhost/compose/config.go
> Update hasura auth to v0.13.2

- nhost/compose/config.go
- postgres image with postgis available
> update postgres image

- nhost/compose/config.go
Related to https://github.com/nhost/nhost/issues/493
> bump nhost/functions to 0.1.6 which uses nodejs v16

- nhost/compose/config.go
- update hasura's version to `v2.13.0`
- update hasura storage's version to `0.2.6`
> bump hasura version

- README.md
- cmd/contact.go
- cmd/dev.go
- cmd/dev_test.go
- internal/ports/default.go
- internal/ports/ports.go
- internal/ports/ports_test.go
- nhost/compose/config.go
- nhost/compose/config_test.go
- nhost/service/endpoints.go
- nhost/service/manager.go
Plug [nhost dashboard](https://github.com/nhost/nhost/tree/main/dashboard) into CLI
> Use nhost dashboard

- nhost/compose/config.go
> bump up hasura auth version

- nhost/service/manager.go
fix: fixes "No such service 'hasura'" problem
Certain versions of `Docker for Mac` don't exit with non-zero exit code for `docker compose kill` if there are no containers running, while others do.
Stop containers only in case if there's at least 1 container is running.
Superceeds https://github.com/nhost/cli/pull/458 and https://github.com/nhost/cli/pull/506
> fix: No such service "hasura"

- cmd/config/pull.go
- cmd/project/init.go
> feat: allow pulling config without overwriting secrets

- clienv/flags.go
> fix: detect git branch correctly

- cmd/dev/up.go
- dockercompose/compose.go
- dockercompose/storage.go
> fix: expose hasura correctly when requested

- cmd/project/init.go
Fixes [#2244](https://github.com/nhost/nhost/issues/2244)
> fix: add newline when appending to gitignore

- dockercompose/graphql.go
- dockercompose/graphql_test.go
- examples/myproject/nhost/metadata/allow_list.yaml
- examples/myproject/nhost/metadata/query_collections.yaml
- examples/myproject/nhost/metadata/rest_endpoints.yaml
Fixes https://github.com/nhost/nhost/issues/2229
> fix: proxy hasura's rest endpoints

- cmd/dev/up.go
- cmd/project/init.go
Fixes https://github.com/nhost/nhost/issues/2253
> fix: add elipsis for consistency

- clienv/clienv.go
> fix: allow uppercase in project name

- cmd/dev/up.go
- dockercompose/compose.go
- nhostclient/graphql/models_gen.go
Mostly useful for dev purposes.
> feat: allow overriding dashboard version

- cmd/config/example.go
- dockercompose/auth_test.go
- dockercompose/main_test.go
- go.mod
- go.sum
- nhostclient/graphql/models_gen.go
- vendor/github.com/nhost/be/services/mimir/model/cuegraph_gen.go
- vendor/github.com/nhost/be/services/mimir/schema/appconfig/hasura_auth.go
- vendor/github.com/nhost/be/services/mimir/schema/schema.cue
- vendor/github.com/nhost/be/services/mimir/schema/schema_gen.graphqls
- vendor/modules.txt
Also adds adjustments for functions custom domains
> feat: add support for webauthn rp id

- .github/workflows/checks.yaml
- .github/workflows/release.yaml
- .github/workflows/wf_build_artifacts.yaml
- Makefile
- cmd/dev/up.go
- flake.nix
- go.mod
- go.sum
- vendor/github.com/nhost/be/services/mimir/schema/schema.cue
- vendor/modules.txt
In addition:
- update schema
- add test that creates a new project and starts it
> feat: added --down-on-error flag to up command

- README.md
style: Enhance README.md with improved styling and formatting
- Improved header and alignment styling for better visual hierarchy
- Added syntax highlighting to code blocks
- Enhanced section titles for better readability
- Ensured all external links open in new tabs
- Used more descriptive alt text for images
chore: Enhance the README.md file for better readability and visual appeal.
The original README.md file lacked visual hierarchy and readability, making it difficult for users to quickly grasp the information. Additionally, code blocks were not highlighted, external links didn't specify opening in new tabs, and images lacked descriptive alt text.
- Improved header styling and alignment to create a clear visual hierarchy.
- Added syntax highlighting to all code blocks for better …
> style: Enhance README.md with improved styling and formatting

- cmd/dev/up.go
- cmd/project/init.go
- nhostclient/graphql/models_gen.go
Fixes https://github.com/nhost/nhost/issues/2831
> fix: hasura wrapper was missing local subdomain under some conditions

- go.mod
- go.sum
- vendor/github.com/nhost/be/services/mimir/schema/appconfig/hasura_auth.go
- vendor/github.com/nhost/be/services/mimir/schema/schema.cue
- vendor/github.com/nhost/be/tools/cuegraph/types/int16.go
- vendor/github.com/nhost/be/tools/cuegraph/types/int8.go
- vendor/github.com/nhost/be/tools/cuegraph/types/uint16.go
- vendor/github.com/nhost/be/tools/cuegraph/types/uint8.go
- vendor/modules.txt
Enhancement
___
- Updated the `github.com/nhost/be` dependency to the latest version (20240909125313-7c9f5c9566d0)
- This update affects both `go.mod` and `go.sum` files
- No other dependencies were changed in this update
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>go.mod</strong><dd><code>Update nhost/be dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
go.mod
<li>Updated the version of github.com/nhost/be dependency from <br>20240908163314-496619d1918a to 20240909125313-7c9f5c9566d0<br>
</details> …
> chore: update schema

- .github/workflows/gen_ai_review.yaml
- nhostclient/graphql/models_gen.go
Enhancement
___
- Update PR Agent action to version 0.26
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>gen_ai_review.yaml</strong><dd><code>Upgrade PR Agent action version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/gen_ai_review.yaml
- Updated PR Agent action from v0.24 to v0.26
</details>
</td>
<td><a href="https://github.com/nhost/cli/pull/937/files#diff-d1e4c772e0acb5ce4891df2dd94ba58ffaf6393e8f75493ec7e10cbce1c4992c">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> chore: update pr-agent to 0.26
