src/commands/init.js
I noticed `POSTGRES_USER` was being set to `postgres_password` and thought it was worth a quick PR.
=> Use correct postgres_user config value

package-lock.json, package.json, src/commands/dev.js, src/commands/init.js, src/migrations/up.sql
- ENV vars can also be used on headers from event triggers
- Applies the local init migration on the server specified with `--endpoint` (fixes https://github.com/nhost/cli/issues/17)
- .env.development is now created even if no ENV vars are fetched (fixes https://github.com/nhost/cli/issues/16)
- TODO: add minio support
=> Event triggers can also use ENV vars for their headers

package-lock.json, package.json, src/commands/dev.js, src/commands/init.js, src/util/compose.js, src/util/config.js, src/util/docker-api.js
Run serverless functions based on files and directories inside a `api/` folder in the project's root directory.
The API server will automatically restart when files changes inside the `api/` folder.
An empty `api/` folder will be created if no `api/` folder exists.
Example code `api/index.js`:
```js
module.exports = (req, res) => {
const { name = "World" } = req.query;
res.send(`Hello ${name}!`);
};
```
I also added better output for the `nhost dev` command.
```bash
$ nhost dev
✔ Local Nhost backend is running!
GraphQL API:	http://localhost:8080/v1/graphql
Hasura Console:	http://localhost:9695
Auth & Storage:	http://localhost:9000
API:		http://localhost:4000
```
Fixes #5
=> Build and run api container

package-lock.json, package.json, src/commands/dev.js
If nhost dev fails or ports are in use:
- cleanup will dump `docker-compose logs` into .nhost/nhost.log to do a post mortem (e.g. invalid metadata will let hasura start but will not start the API)
- more error reporting, e.g. if `docker compose down` fails or ...
- added port detection to cli, so before nhost continues, it will check available ports.
If using Ctrl-C to interrupt, the nhost dev command will still continue to be executed. Since log file dumping takes some time, there is the case, that nhost dev will report everything up and running while cleanup will try to tear it down.
=> More error reporting, some port checking and dumping log files of containers in case of error

src/commands/init.js
The fixes a small bug in the init routine for the .gitignore references where if a use has an existing file the initial reference to .nhost will be appended to the last entry instead of on a new line. Possibly causing them to checkin the .nhost folder as part of an initial commit.. 
Before 
`/.next.nhost
api/node_modules`
After
`/.next
.nhost
api/node_modules`
=> small bug in gitignore on init project

src/commands/init.js, src/util/compose.js
There is a addresses two small bugs in the CLI init process 
- an existing .env.development file will be overwritten and lose existing values 
- project_env_vars will be overwritten by the subsequent call to write the REGISTRATION_CUSTOM_FIELDS block
=> fixing bug with overwriting .env.development

src/commands/init.js
**Reasoning** - Bootstrapping with `nhost init` does not append `.env.development` to `.gitignore` - pushing the file to repo.
**Changes** - appends `.env.development` to files being written to `.gitignore` during `nhost init`.
=> Adds env.dev to ignored files

nhost/nhost.go
If github returns an `API rate limit exceeded` error it wont respond with releases.
Return an error instead of panicing
=> fix: out of range error during searching for new versions

.github/workflows/release.yaml
Instead of relying on the github api, host an `releases.json` file on github pages. Use this file to fetch all releases later on.
=> chore: add releases.json file

nhost/nhost.go
Use the new generated releases.json file for checking the updates instead of using the github api.
=> chore: use releases.json for updates

nhost/nhost.go
- Bump up hasura auth to v0.3.2 (https://github.com/nhost/hasura-auth/releases/tag/v0.3.2)
=> Bump up Hasura Auth to v0.3.2

environment/environment.go, environment/execution.go, hasura/commonmetadataops.go, hasura/hasura.go
**Approach**
1. Let the existing default process complete, and the environment get up and running. This includes `hasura migrate apply`, `metadata export` and `metadata apply`.
2. Call the Hasura `/v1/metadata` endpoint to fetch inconsistent metadata.
3. Based on the schema in which the inconsistency exists, restart the equivalent container.
4. Let the container handle the applying of its own metadata.
5. Restart the health-checks to wait for the specific container to get active.
NOTE: This approach will effectively only work to restart the `auth` and `storage` containers, for obvious reasons. And that is all we need for now.
**Test Case**
I've not added test cases inside the code for this fix, but I used an existing metadata inconsistency in my own app to test this solution. And it …
=> fix: manage metadata updates from auth and storage

nhost/nhost.go
Due to Podman's permissions, the Postgres mount fails when it tries to `chown` and `chmod` the database volume. Mounting with the [`Z` option](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) resolves this issue.
I had to change the Postgres image to use `HostConfig.Binds` instead of `HostConfig.Mounts` since it does not appear to be possible to set the `Z` option using the latter.
This fixes https://github.com/nhost/cli/issues/148 and provides the remaining support needed for https://github.com/nhost/cli/issues/139
=> Mount database path with Z option

nhost/nhost.go
The `HASURA_GRAPHQL_ADMIN_SECRET` was not formatted with `Sprintf` ending up with a value prefixed with `%s`
=> fix: do not prefix `%s` prefix to the admin secret

cmd/dev.go, nhost/service/launcher.go
Depending on project complexity the `nhost up` command may take a few minutes (pulling docker images on first run, downloading node_modules, etc) to complete.
Add a flag `--start-timeout` with default value of 5 minutes
=> Added --start-timeout flag with default value of 5 minutes

nhost/compose/config.go, nhost/service/manager.go
- Use named docker volumes to persist `node_modules` from root and functions folder to prevent incompatibilities with host OS
- Edit the slow start message
=> Named volumes for node_modules

nhost/compose/config.go
Use the new `hasura-storage` **v0.2.4** which introduces `--api-root-prefix` flag, that allows CLI to set expected prefix for all API calls to storage service. Also fixes https://github.com/nhost/cli/issues/311
=> Bump hasura-storage and fix presigned url issue

cmd/compose.go, cmd/dev.go, cmd/logs.go, nhost/compose/config.go, nhost/compose/paths.go, nhost/compose/paths_test.go, nhost/compose/wrapper.go, nhost/service/manager.go
- Change docker volume mount path for postgres to avoid permission issue with `seeds.applied` file
- scope data folders for `minio`, `mailhog` and `postgres` with branch name
A user can do the following to avoid loosing postgres data after upgrade:
- `mkdir -p .nhost/data/[branch]/db`
- `mv .nhost/data/db/[branch] .nhost/data/[branch]/db/pgdata` (prepend with sudo in case of permission issue)
=> fix: permission issue with seeds.applied file

cmd/logs.go, nhost/compose/config.go, nhost/service/manager.go
fix: ensuring S3 bucket creation only if minio is running
fix: don't generate `docker-compose.yaml` file in `logs` subcommand
chore: bump nhost/functions to 0.1.3
=> A few fixes

cmd/pull.go, cmd/pull_test.go
Closes https://github.com/nhost/cli/issues/218
Not all schema objects are pulled on `nhost init` with `--remote` flag
Use pgdump API and pull all objects from all schemas except `auth`, `storage`, `pg_*`, `hdb_*`
=> Pull objects on remote init from all schemas except "auth", "storage", "pg_*", "hdb_*"

nhost/compose/config.go, nhost/compose/wrapper.go, nhost/service/manager.go, nhost/utils.go
Use custom postgres image `nhost/postgres:14.5` based on `postgres:14.5`
With the work done to move away from AWS RDS, we are using a custom postgres image with specific roles for all services.
Start using the custom postgres image and pass in the right roles to all services
This version should only be used by projects already migrated from RDS.
=> Use custom nhost/postgres image with correct roles

internal/git/reference_getter_with_fallback.go
Fixes detection of `.git` folder location for submodules
`nhost dev` didn't work for submodules
=> Fix detecting the location of .git for submodules

hasura/hasura.go
1. Process only stdout of the command `hasura version`
2. Do not download hasura cli if the user 'hardcoded" the binary, instead error if it isn't the version we expect.
When trying to detect the version of `hasura` we'd process both stdout and stderr but this can lead to errors as sometimes `hasura` will print debug statements under stderr, for instance:
```
{"level":"info","msg":"Help us improve Hasura! The cli collects anonymized usage stats which\nallow us to keep improving Hasura at warp speed. To opt-out or read more,\nvisit [https://hasura.io/docs/latest/graphql/core/guides/telemetry.html\n](https://hasura.io/docs/latest/graphql/core/guides/telemetry.html/n)","time":"2022-09-19T19:44:35Z"}
{"level":"info","msg":"hasura cli","time":"2022-09-19T19:44:35Z","version":"v2.10.1"}
```
In …
=> fix: treat output of hasura cli correctly and honor custom binary

nhost/utils.go, nhost/utils_test.go
`nhost up` may fail if project's folder name contains certain symbols like `(` or `)`. The project name for docker compose is comprised of a base name + random string.
Filter out non alphanumeric and hyphen symbols in base name.
=> fix: Fix docker compose project generation

hasura/hasura.go
Use native arm build of hasura cli on arm architecture
amd64 hasura cli works fine if `rosetta 2` installed, otherwise it doesn't run
=> Use native hasura cli on ARM arch

hasura/hasura.go
Closes https://github.com/nhost/cli/issues/350
Long-standing bug with `nhost init --remote` which kept failing with weird error `fork/exec $PROJECT_NAME/.nhost/hasura: no such file or directory`
Apparently reproducible only if called from homedir 😄 
The reason is that the global var `nhost.ROOT` is mutated in https://github.com/nhost/cli/blob/fe711fb4f867370dad802a63ae922aeaac403dbf/nhost/vars.go#L170-L188 which may lead to incorrect path calculation when hasura client is initialised.
Using `nhost.ROOT` var (which doesn't change) for hasura path forming
This is a quick fix, a proper refactor is needed to remove global vars mutations and weird `nhost.UpdateLocations()` fun
=> Fix project init with --remote flag from homedir

nhost/compose/config.go
Avoid infinite loop on lock file change. Closes https://github.com/nhost/cli/issues/402
=> Bump nhost/functions to 0.1.7

nhost/compose/config.go
Previous release uses 2.15.2 which isn't completely released by hasura
=> hotfix: use hasura v2.15.1

get.sh
get.sh failed to match `aarch64` on Debian arm 
add `aarch64` to get.sh `archstr` matching to download correct release
=> fix: add 'aarch64' to 'arch' matching

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.7.5.
=> chore: bump nhost/dashboard to 0.7.5

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.7.6.
=> chore: bump nhost/dashboard to 0.7.6

nhost/compose/config.go
`nhost up` does not succeed.
hasura/graphql-engine (v2.15.1) image has been removed from the repository.
ref: https://hub.docker.com/r/hasura/graphql-engine
I have updated the version of hasura/graphql-engine.
=> fix: update hasura/graphql-engine to v2.15.2

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.7.8.
=> chore: bump nhost/dashboard to 0.7.8

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.7.13.
=> chore: bump nhost/dashboard to 0.7.13

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.8.0.
=> chore: bump nhost/dashboard to 0.8.0

nhost/compose/config.go, nhost/compose/config_test.go
`host.docker.internal` points to the host machine in `Docker for Mac`, but on some other installations f.e. on Linux it's not set.
Impossible to talk to services running on the host machine on docker installations without `host.docker.internal` extra host.
=> Add host.docker.internal as an extra host for systems where it's not set automatically

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.9.6.
=> chore: bump nhost/dashboard to 0.9.6

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.9.7.
=> chore: bump nhost/dashboard to 0.9.7

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.9.8.
=> chore: bump nhost/dashboard to 0.9.8

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.9.9.
=> chore: bump nhost/dashboard to 0.9.9

cmd/init.go, nhost/types.go
Include region's name in App struct.
`nhost init --remote` was failing due to the old hasura endpoint deprecation.
Use new hasura endpoint.
=> fix: Use the new hasura endpoint when initializing remote project

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.9.10.
=> chore: bump nhost/dashboard to 0.9.10

nhost/nhost.go
Set `hasura_graphql_enable_remote_schema_permissions` default value to `true` on project init.
This setting is set to `true` on the cloud, while it's `false` by default for new projects bootstrapped with CLI.
=> fix: Change default value of "hasura_graphql_enable_remote_schema_permissions"

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.10.1.
=> chore: bump nhost/dashboard to 0.10.1

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.11.2.
=> chore: bump nhost/dashboard to 0.11.2

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.11.6.
=> chore: bump nhost/dashboard to 0.11.6

hasura/client.go, nhost/service/manager.go
I've added a last step to reload Hasura Metadata for `nhost up`.
When using a serverless function as a Remote Schema, Hasura had issues because the remote schema was not always available for Hasura when it needed to be.
Reload the Hasura metadata as a last step.
Fixes: https://github.com/nhost/nhost/issues/1577
=> Reload metadata to fix remote schemas from functions

nhost/service/manager.go
Add a guard check to prevent CLI from failing on migrations/metadata apply if those folders don't exist.
=> Check whether migrations and metadata folders exist

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.11.13.
=> chore: bump nhost/dashboard to 0.11.13

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.11.17.
=> chore: bump nhost/dashboard to 0.11.17

nhost/compose/config.go, nhost/compose/config_test.go
This PR bumps the Nhost Dashboard Docker image to version 0.13.2.
=> chore: bump nhost/dashboard to 0.13.2

nhost/compose/config.go
This PR bumps the Nhost Dashboard Docker image to version 0.13.3.
=> chore: bump nhost/dashboard to 0.13.3

nhost/compose/config.go
This PR bumps the Nhost Dashboard Docker image to version 0.13.9.
=> chore: bump nhost/dashboard to 0.13.9

nhost/compose/config.go, nhost/compose/config_test.go, nhost/compose/hostnames.go, nhost/compose/svc_storage.go
When we launched the new SSL endpoints the old one should've worked as usual for backward compatibility reasons. However, due to a bug, requesting presigned urls to the storage using the old endpoint returned an invalid url pointing to the new endpoint.
This PR fixes that behaviour and ensures that presigned URLs for the same endpoint are return correctly.
=> fix: set external url for http-based storage correctly

nhost/compose/config.go
This PR bumps the Nhost Dashboard Docker image to version 0.14.1.
=> chore: bump nhost/dashboard to 0.14.1

nhost/compose/config.go
This PR bumps the Nhost Dashboard Docker image to version 0.14.8.
=> chore: bump nhost/dashboard to 0.14.8

nhost/compose/config.go
This PR bumps the Nhost Dashboard Docker image to version 0.16.1.
=> chore: bump nhost/dashboard to 0.16.1

clienv/filesystem.go, cmd/dev/up.go, cmd/project/init.go, dockercompose/compose.go
Solves https://github.com/nhost/nhost.toml/issues/1
The idea is as follows to replace the values of environment variables in `[[ global.environment]]` with the values defined in `.env.development`. It is important to note that this functionality only REPLACES, it does NOT add environment variables, for the override to work the env var needs to be defined first.
=> feat: allow using .env.development to override defined env vars

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.16.11.
=> chore: bump nhost/dashboard to 0.16.11

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.16.12.
=> chore: bump nhost/dashboard to 0.16.12

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.16.13.
=> chore: bump nhost/dashboard to 0.16.13

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.16.14.
=> chore: bump nhost/dashboard to 0.16.14

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.17.0.
=> chore: bump nhost/dashboard to 0.17.0

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.17.1.
=> chore: bump nhost/dashboard to 0.17.1

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.17.2.
=> chore: bump nhost/dashboard to 0.17.2

clienv/wf_app_info.go, cmd/config/config.go, cmd/config/pull.go, cmd/config/show.go, cmd/config/validate.go, cmd/config/validate_test.go, cmd/dev/up.go, cmd/project/init.go, cmd/secrets/create.go, cmd/secrets/delete.go, cmd/secrets/list.go, cmd/secrets/secrets.go, cmd/secrets/update.go
Solves #465
If no subdomain is specified, defaults to the linked project.
```
❯ nhost config validate --remote
Getting secrets...
Config is valid!
❯ nhost --subdomain yuimvxekebusfkiwfexo config validate --remote
Getting secrets...
main.go:59: failed to validate config: failed to render config tempolate: failed to render template: variable not found: secrets.APPLE_CLIENT_ID
exit status 1
```
```
❯ nhost secrets create MY_SECRET 456
Secret created successfully!
❯ nhost --subdomain yuimvxekebusfkiwfexo secrets create MY_SECRET 123
Secret created successfully!
```
=> feat: allow specifying subdomain when working with remote environments

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.17.9.
=> chore: bump nhost/dashboard to 0.17.9

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.17.18.
=> chore: bump nhost/dashboard to 0.17.18

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.17.20.
=> chore: bump nhost/dashboard to 0.17.20

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.19.0.
=> chore: bump nhost/dashboard to 0.19.0

cmd/config/pull.go, cmd/dev/up.go
`nhost config pull` aborts when users passes in 'Y' (upper case). 
During the migration [away from Cobra cli](https://github.com/nhost/cli/pull/667/files#diff-05feb559e87ca0f962a3b449103033c6416fefe957077a75ccc69e29fd82aa19R67), a corner case was missed to support upper case from the user prompt.
```
nhost config pull
- nhost/nhost.toml already exists. Do you want to overwrite it? [y/N] Y
main.go:59: aborting
```
Extend the check to include upper case of 'Y' in the two cases found wher
Tested by building locally and getting a positive output 
``` ~/go/src/tools/cli/nhosttest config pull
- nhost/nhost.toml already exists. Do you want to overwrite it? [y/N] Y
- .secrets already exists. Do you want to overwrite it? [y/N] Y
Pulling config from Nhost...
Getting secrets list from Nhost... …
```
=> fix:Add upper case verification for cli prompts

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.2.
=> chore: bump nhost/dashboard to 0.20.2

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.3.
=> chore: bump nhost/dashboard to 0.20.3

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.6.
=> chore: bump nhost/dashboard to 0.20.6

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.7.
=> chore: bump nhost/dashboard to 0.20.7

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.17.
=> chore: bump nhost/dashboard to 0.20.17

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.20.
=> chore: bump nhost/dashboard to 0.20.20

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.25.
=> chore: bump nhost/dashboard to 0.20.25

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.26.
=> chore: bump nhost/dashboard to 0.20.26

dockercompose/compose.go
This PR bumps the Nhost Dashboard Docker image to version 0.20.27.
=> chore: bump nhost/dashboard to 0.20.27

clienv/clienv.go, clienv/flags.go, cmd/config/validate_test.go, cmd/dev/down.go, cmd/dev/up.go, cmd/dockercredentials/get.go, dockercompose/compose.go, dockercompose/dockercompose.go, dockercompose/postgres.go, dockercompose/postgres_test.go
Bind mounts seem to be causing issues either with SELINUX and/or other combinations. Move to docker volumes for higher compatibility.
In addition add `--volumes` to `nhost down` to delete volumes.
=> feat: migrate postgres data to a docker volume for compatibility

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.3.0.
=> chore: bump nhost/dashboard to 1.3.0

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.4.0.
=> chore: bump nhost/dashboard to 1.4.0

cmd/dev/up.go, dockercompose/dockercompose.go
This is to avoid confusing the user with transient metadata inconsistencies.
=> fix: hide apply metadata errors and verify metadata in the end

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.6.7.
=> chore: bump nhost/dashboard to 1.6.7

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.12.0.
=> chore: bump nhost/dashboard to 1.12.0

cmd/configserver/configserver.go, cmd/configserver/local.go, cmd/configserver/local_test.go, dockercompose/compose.go, dockercompose/configserver.go
File descriptor might change if users revert a file using git or similar. To avoid that issue we:
1. Mount the parent folder instead of the file
2. Open/Write/Close the file each time instead of relying on readers and writers
=> feat: configserver: use filepaths to avoid disconnected fds

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.12.2.
=> chore: bump nhost/dashboard to 1.12.2

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.13.2.
=> chore: bump nhost/dashboard to 1.13.2

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.13.3.
=> chore: bump nhost/dashboard to 1.13.3

Makefile, flake.nix, software/sofware.go
=> fix: don't remove `v` from the version

cmd/config/example.go, cmd/run/config_example.go, dockercompose/compose.go, dockercompose/main_test.go, dockercompose/run_test.go, examples/myproject/functions/echo.ts, examples/myproject/nhost/nhost.toml, go.mod, go.sum, nhostclient/graphql/models_gen.go, vendor/github.com/nhost/be/services/mimir/graph/generated/generated.go, vendor/github.com/nhost/be/services/mimir/graph/m_replace_config_raw_json.go, vendor/github.com/nhost/be/services/mimir/graph/schema.resolvers.go, vendor/github.com/nhost/be/services/mimir/model/cuegraph_gen.go, vendor/github.com/nhost/be/services/mimir/schema/schema.cue, vendor/github.com/nhost/be/services/mimir/schema/schema.graphqls, vendor/github.com/nhost/be/services/mimir/schema/schema_gen.graphqls, vendor/modules.txt
Enhancement, Bug fix
___
- Added `Autoscaler` field with `nil` value to various configurations in multiple files.
- Updated Docker Compose functions to use a dynamic image version format that includes the Node.js version.
- Updated Node.js version from 18 to 20 in the example project configuration.
- Updated Go version from 1.22.3 to 1.22.4 and updated `github.com/nhost/be` dependency version in `go.mod`.
- Updated checksums for dependencies in `go.sum`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>example.go</strong><dd><code>Add `Autoscaler` field to configurations in example command</code></dd></summary>
<hr>
cmd/config/example.go
<li>Added …
=> feat: added support for nodejs 20 alongside nodejs 18

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.19.0.
___
enhancement
___
- Updated the Nhost Dashboard Docker image version to 1.19.0 in the `cmd/dev/up.go` file.
- This change ensures that the latest features and fixes in the Nhost Dashboard are included.
___
<tr>
<td>
<details>
<summary><strong>up.go</strong><dd><code>Bump Nhost Dashboard version to 1.19.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
cmd/dev/up.go
<li>Updated the default value for the <code>flagDashboardVersion</code> to …
=> chore: bump nhost/dashboard to 1.19.0

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 1.25.0.
=> chore: bump nhost/dashboard to 1.25.0

clienv/clienv.go, clienv/flags.go, cmd/config/validate_test.go, cmd/dev/hasura.go, cmd/dev/up.go, cmd/dockercredentials/get.go, dockercompose/ai.go, dockercompose/ai_test.go, dockercompose/auth.go, dockercompose/auth_test.go, dockercompose/compose.go, dockercompose/docker.go, dockercompose/graphql.go, dockercompose/graphql_test.go, dockercompose/postgres.go, dockercompose/postgres_test.go, dockercompose/run.go, dockercompose/run_test.go, dockercompose/storage.go, dockercompose/storage_test.go, dockercompose/url.go, nhostclient/graphql/models_gen.go
Adds `local-subdomain` flag to set new-style's subdomain (old style still works):
```
❯ nhost --local-subdomain 127-0-0-1 up
Checking versions...
✅ Auth is already on a recommended version: 0.30.0
🟡 Storage is not on a recommended version. Recommended: 0.6.1
More info: https://github.com/nhost/hasura-storage/releases
🟡 PostgreSQL is not on a recommended version. Recommended: 14.11-20240515-1, 14.11-20240718-1, 15.6-20240718-1, 16.2-20240718-1
More info: https://hub.docker.com/r/nhost/postgres
🟡 Hasura is not on a recommended version. Recommended: v2.38.0-ce
🟡 A new version of Nhost CLI is available: v1.21.0
You can upgrade the CLI by running `nhost sw upgrade`
More info: https://github.com/nhost/cli/releases
Setting up Nhost development environment...
Starting Nhost development …
```
=> feat: allow selecting local subdomain

cmd/dev/up.go, go.mod, go.sum, nhostclient/graphql/models_gen.go, vendor/github.com/nhost/be/services/mimir/schema/schema.cue, vendor/modules.txt
This PR bumps the Nhost Dashboard Docker image to version 1.27.0.
=> chore: bump nhost/dashboard to 1.27.0

cmd/dev/up.go, dockercompose/compose.go
=> feat: added option to override CA certificates

go.mod, go.sum, nhostclient/graphql/models_gen.go, vendor/modules.txt
Enhancement
___
- Updated generated GraphQL models in `nhostclient/graphql/models_gen.go`:
- Removed several unused structs and enums
- Added `InferFunctionPermissions` field to Hasura settings structs
- Updated `github.com/nhost/be` dependency to latest version
- Updated Go module checksums accordingly
___
<tr>
<td>
<details>
<summary><strong>models_gen.go</strong><dd><code>Update generated GraphQL models</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
nhostclient/graphql/models_gen.go …
=> fix: update generated models

cmd/config/example.go, cmd/configserver/local_test.go, dockercompose/main_test.go, go.mod, go.sum, nhostclient/graphql/models_gen.go, project/config.go, vendor/github.com/nhost/be/services/mimir/graph/generated/generated.go, vendor/github.com/nhost/be/services/mimir/model/cuegraph_gen.go, vendor/github.com/nhost/be/services/mimir/schema/schema.cue, vendor/github.com/nhost/be/services/mimir/schema/schema_gen.graphqls, vendor/modules.txt
Enhancement
___
- Added SMTP configuration support for Grafana in the ConfigObservability struct
- Created new structs and fields for SMTP configuration in the GraphQL models
- Updated test and default configurations to include the new SMTP field (set to nil)
- Updated the nhost/be dependency to the latest version
- Modified relevant files to accommodate the new SMTP configuration options
___
<tr>
<td>
<details>
<summary><strong>example.go</strong><dd><code>Add Grafana SMTP Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> chore: update schema

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 2.0.7.
=> chore: bump nhost/dashboard to 2.0.7

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 2.1.0.
=> chore: bump nhost/dashboard to 2.1.0

cmd/dev/up.go, nhostclient/graphql/models_gen.go
This PR bumps the Nhost Dashboard Docker image to version 2.7.0.
=> chore: bump nhost/dashboard to 2.7.0

clienv/wf_app_info.go, nhostclient/graphql/models_gen.go
bug_fix
___
- Fixed the app lookup logic to include searching within organizations, not just workspaces.
- Renamed a variable for better clarity in the code.
- Improved error handling by providing a more descriptive error message when an app is not found.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>wf_app_info.go</strong><dd><code>Fix and enhance app lookup in organizations and workspaces</code></dd></summary>
<hr>
clienv/wf_app_info.go
<li>Changed the variable name from <code>workspaces</code> to <code>resp</code> for clarity.<br> <li> Added logic to iterate over <code>Organizations</code> to find apps by subdomain.<br> <li> Enhanced error message for failed …
=> fix: look for projects in organizations

dockercompose/ai.go, dockercompose/ai_test.go
Bug fix
___
- Fixed the `NHOST_STORAGE_URL` in the `ai` function to include the `/v1` path.
- Updated the corresponding test in `ai_test.go` to reflect the corrected `NHOST_STORAGE_URL`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ai.go</strong><dd><code>Corrected NHOST_STORAGE_URL path in ai function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dockercompose/ai.go
- Updated the `NHOST_STORAGE_URL` to include the `/v1` path.
</details>
</td>
<td><a href="https://github.com/nhost/cli/pull/930/files#diff-eaefd76d4b099b72d062805dee9d91cf55d1f6c46ff5aaa061d706d1535aa023">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> fix: set the correct variable

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 2.9.0.
=> chore: bump nhost/dashboard to 2.9.0

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 2.10.0.
___
enhancement
___
- Updated the Nhost Dashboard Docker image version in the `cmd/dev/up.go` file from 2.9.0 to 2.10.0.
- This change ensures that the latest features and fixes in version 2.10.0 are utilized.
___
<tr>
<td>
<details>
<summary><strong>up.go</strong><dd><code>Update Nhost Dashboard Docker image version to 2.10.0</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
cmd/dev/up.go
<li>Updated the default Nhost Dashboard Docker image version from 2.9.0 to <br>2.10.0.<br>
</details>
</td>
<td><a href="https://github.com/nhost/cli/pull/931/files#diff-b5263420bb6de52a7fe9a32d559b07 …
=> chore: bump nhost/dashboard to 2.10.0

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 2.13.0.
=> chore: bump nhost/dashboard to 2.13.0

dockercompose/compose.go, examples/myproject/functions/crash.ts, examples/myproject/functions/error.ts, examples/myproject/nhost/nhost.toml, go.mod, go.sum, vendor/github.com/nhost/be/services/mimir/schema/appconfig/hasura_storage.go, vendor/github.com/nhost/be/services/mimir/schema/schema.cue, vendor/modules.txt
Enhancement
___
- Upgraded Node.js version to 22 in functions
- Updated nhost/functions image to 1.4.0-beta1
- Updated nhost/be dependency to latest version
- Modified example project configuration
___
<tr>
<td>
<details>
<summary><strong>compose.go</strong><dd><code>Update nhost/functions image version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dockercompose/compose.go
- Updated nhost/functions image version to 1.4.0-beta1
</details>
</td>
<td><a href="https://github.com/nhost/cli/pull/941/files#diff-67d473eea1a53a8257f9079830 …
=> feat: added support for nodejs22

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 2.15.0.
=> chore: bump nhost/dashboard to 2.15.0

cmd/dev/up.go
This PR bumps the Nhost Dashboard Docker image to version 2.28.0.
=> chore: bump nhost/dashboard to 2.28.0
